---

  - name: tag new image as '{{ _btag_iter }}'  ==>>  {{ _cur_dockimg.fullname }}
    community.docker.docker_image:
      name: "{{ _build_img_tmpname }}:latest"
      repository: "{{ _cur_dockimg.fullname }}:{{ _btag_iter }}"
      force_tag: yes
      source: local


  - set_fact:
     _dbuild_meta: >-
       {{ _dbuild_meta | combine({'tags': [_btag_iter]}, 
             recursive=True, list_merge='append')
       }}

