---

    ## unpack archive according to config
  - set_fact:
      _tmp_unarchive_args: >-
        {{ dict() | combine(_iter_packinst.destination.config,
             {  'src': _tmp_last_mvn_artifact_status.dest,
               'dest': _iter_packinst.destination.path,
               'remote_src': true
             }, recursive=True, list_merge='append')
        }}


  - block:

        # create dir for temporary holding unarchived content
      - ansible.builtin.tempfile:
          state: directory
        register: _tmp_unpack_dir

      - set_fact:
          _tmp_unarchive_args: >-
            {{ _tmp_unarchive_args
             | combine({ 'dest': _tmp_unpack_dir.path }) }}

    when: >-
       _iter_packinst.destination.singlefile
       or _iter_packinst.destination.install


  - name: >-
      unpack maven artifact '{{ _iter_packinst.name }}'
       ==>>  {{ _cur_dockimg.fullname }}
    ansible.builtin.unarchive: "{{ _tmp_unarchive_args }}"


  - name: delete maven artifact file
    ansible.builtin.file:
      path: "{{ _tmp_last_mvn_artifact_status.dest }}"
      state: absent


  - block:

      - set_fact:
          _tmp_post_inst_artpath: "{{ _tmp_unpack_dir.path }}"


      - block:

          # get content of tmp unpack dir
          - ansible.builtin.find:
              paths: "{{ _tmp_unpack_dir.path }}"
              recurse: yes
            register: _tmp_unarchive_content

          # check that it contains just a single file
          - ansible.builtin.assert:
              that:
                - _tmp_unarchive_content.matched == 1
              fail_msg: >-
                As running maven artifact unpacking in single file mode
                expected exactly one file in maven archive, but
                got: {{ _tmp_unarchive_content.matched }}

          # move that file to final destination
          - ansible.builtin.command: >-
              mv '{{ (_tmp_unarchive_content.files | first).path }}'
                 '{{ _iter_packinst.destination.path }}'

          - set_fact:
              _tmp_post_inst_artpath: "{{ _iter_packinst.destination.path }}"

        when: _iter_packinst.destination.singlefile


        ## if downloaded maven artifact is actually a
        ## installer optionally run it
      - include_tasks: post_installer.yml
        vars:
          mvn_artifact_dlpath: "{{ _tmp_post_inst_artpath }}"
        when: _iter_packinst.destination.install


      # remove tmp unpack dir
      - ansible.builtin.file:
          path: "{{ _tmp_unpack_dir.path }}"
          state: absent

    when: >-
       _iter_packinst.destination.singlefile
       or _iter_packinst.destination.install


    ## test unpacked checksum
  - include_tasks: do_checksums.yml
    loop: >-
      {{ _iter_packinst.destination.unpacking.checksums | dict2items() }}
    loop_control:
      loop_var: _checksums_iter
    vars:
      checksum_params:
        default_file: "{{ _iter_packinst.destination.path }}"

