---

    ##
    ## TODO: technically it would be cleaner to remove this again at the end, but is it really worth the effort??
    ##
  - name: >-
      make sure target system is prepared for maven module
       ==>>  {{ _cur_dockimg.fullname }}
    ansible.builtin.pip:
      name: lxml

  - name: >-
      get maven artifact '{{ _iter_packinst.name }}'
       ==>>  {{ _cur_dockimg.fullname }}
    community.general.maven_artifact: "{{ _iter_packinst.config }}"
    register: _tmp_last_mvn_artifact_status


    ## if provided compare checksums given by pkg cfg
  - include_tasks: do_checksums.yml
    loop: >-
      {{ _iter_packinst.checksums | dict2items() }}
    loop_control:
      loop_var: _checksums_iter
    vars:
      checksum_params:
        default_file: "{{ _tmp_last_mvn_artifact_status.dest }}"


    ## handle unpacking when requested
  - include_tasks: handle_unpacking.yml
    when: _iter_packinst.destination.unpacking


    ## if downloaded maven artifact is actually a
    ## installer optionally run it (only when no unpacking is
    ## involved as unpacking already calls post_installer internally)
  - include_tasks: post_installer.yml
    vars:
      mvn_artifact_dlpath: "{{ _tmp_last_mvn_artifact_status.dest }}"
    when: >-
      not _iter_packinst.destination.unpacking
      and _iter_packinst.destination.install

