---

  - set_fact:
      _tmp_pinst_handled: false
      _tmp_pset_extra_args: >-
        {{ distro_pinst_extra_args | default({}, True)
         | combine({
             'auto_version': _autovcfg_iter,
             'os_family': ansible_os_family
           })
        }}


  - include_tasks: pinst_alpine.yml
    when: ansible_os_family == "Alpine"


  - include_tasks: pinst_debian.yml
    when: ansible_os_family == "Debian"


  - name: >-
      standard distro package installs / removes (fallback) 
       ==>>  {{ _cur_dockimg.fullname }}
    ansible.builtin.package: "{{ _iter_packinst }}"
    loop: >-
      {{ _cur_dockimg.packages.distro
       | smabot.containers.to_psets(**_tmp_pset_extra_args) }}
    loop_control:
      loop_var: _iter_packinst
    when: _tmp_pinst_handled is falsy

