---

  - name: >-
      check that source '{{ _cpimg_files_iter.value.src_rel }}'
      exists  ==>>  {{ copy_to_image_args_normed.image_id }}
    ansible.builtin.stat:
      path: "{{ _cpimg_files_iter.value.src }}"
    become: no
    delegate_to: localhost
    register: _result
    failed_when: 
      - not _result.stat.exists


    ##
    ## note: strangely enough, copy file to file only works when all
    ##   parent dir's pre exist and cannot be tweaked to handle dir
    ##   creation internally (but it works when it is used for copying
    ##   directories), so we do it ourselves here "manually"
    ##
  - name: assure parent dir exists on remote
    ansible.builtin.file:
      state: directory
      path: "{{ _cpimg_files_iter.value.copy_api.dest | dirname }}"
      owner: "{{ _cpimg_files_iter.value.copy_api.owner | default(omit) }}"
      group: "{{ _cpimg_files_iter.value.copy_api.group | default(omit) }}"
      mode: >-
        {{ _cpimg_files_iter.value.copy_api.directory_mode | default(omit) }}


  - name: >-
      copy file / dir '{{ _cpimg_files_iter.value.src_rel }}' to
      image  ==>>  {{ copy_to_image_args_normed.image_id }}
    ansible.builtin.copy: "{{ _cpimg_files_iter.value.copy_api }}"

