---

  docker_build_defaults:

    defaults:

      images: 

        '*':  ## means any owner

          '*':  ## means any image
  
            environment:
  
              static:
  
                ##
                ## note: some debian tooling like dpg needs this var set sometimes
                ##   to avoid interactive querying
                ##
                ## note.2: obviously this var is not needed when distro is not 
                ##   debian based, but it does not really hurt either, so dont 
                ##   bother to make this distro specific
                ##
                DEBIAN_FRONTEND: noninteractive

            packages:

              distro:

                bundles:

                  ##
                  ## predefined optional common standard bundles
                  ##
                  bundles:

                    git:
                      packages:
                        git:
                        openssh-client:

                    python:
                      ##
                      ## enabling this on default seems a very
                      ## sensable idea on 2nd thought
                      ##
                      enable: true
                      packages:
                        python3:
                        python3-pip:
                          os_overwrites:
                            alpine:
                              name: py3-pip

