---

###
### TODO: this whole role is workaround for a strange bug with updating facts from collection modules, remove it when it is not needed anymore, see corresponding role for merge vars for details
###

  - name: "{{ compute_contenv_args.task_name }}"
    smabot.containers.compute_container_env:
      config_ansvar: "{{ compute_contenv_args.config_ansvar }}"
      extra_env: "{{ compute_contenv_args.extra_env | default(omit, True) }}"
    register: _tmp_modres_

    ##
    ## note: set to correct docker user so user specific stuff 
    ##   like $HOME expands correctly
    ##
    become: yes

    ##
    ## note: also important to use the "right" become method here, 
    ##   as sudo has only a very limited core env of the impersonated 
    ##   user (at least on default settings), and see's not nearly 
    ##   all the vars one would get when doing a normal login as this user
    ##
    become_method: su
    become_user: "{{ _cur_dockimg.docker_user | default('root', True) }}"


  - set_fact:
      "{{ compute_contenv_args.config_ansvar }}": "{{ _tmp_modres_.normalized }}"

