---

  # TODO: is there more senseable stuff to do here


  - name: remove temporary distro packages again  ==>>  {{ _cur_dockimg.fullname }}
    include_tasks: packages/distro/main.yml
    vars:
      distro_pinst_extra_args:
        rmtmp: true


  - name: clear pip caches
    ansible.builtin.command:
      cmd: >-
        {{ _pip_exe_iter }} cache purge
    failed_when: false
    loop:
      - pip
      - pip3
      - python -m pip
      - python3 -m pip
    loop_control:
      loop_var: _pip_exe_iter


  - include_tasks: clean_debian.yml
    when: ansible_os_family == "Debian"


  - name: clear image install meta dir
    ansible.builtin.file:
      path: "{{ _cur_dockimg.install_meta.basedir }}"
      state: absent
    when: not _cur_dockimg.install_meta.keep

