---

  docker_build_defaults:

    defaults:

      images: 

        '*':  ## means any owner

          '*':  ## means any image

            ##
            ## note: entrypoint setting is a point which differs a
            ##   bit more compared to docker build, there is no real
            ##   possibility with docker committing to not set / unset
            ##   entrypoint, and on default it sets something which does
            ##   not work like most docker using programs expects images
            ##   to behave on default, so setting it explicitly to this
            ##   here mimics default docker builder behaviour imho quite
            ##   closely, as default it can obviously be overwritten by
            ##   images which want this
            ##
            entrypoint:
              - "/bin/sh"
              - "-c"

            environment:
  
              static:
  
                ##
                ## note: some debian tooling like dpg needs this var set sometimes
                ##   to avoid interactive querying
                ##
                ## note.2: obviously this var is not needed when distro is not 
                ##   debian based, but it does not really hurt either, so dont 
                ##   bother to make this distro specific
                ##
                DEBIAN_FRONTEND: noninteractive


            packages:

              distro:

                bundles:

                  ##
                  ## predefined optional common standard bundles
                  ##
                  bundles:

                    git:
                      packages:
                        git:
                        openssh-client:

                    python:
                      ##
                      ## enabling this on default seems a very
                      ## sensable idea on 2nd thought
                      ##
                      enable: true
                      packages:
                        python3:
                        python3-pip:
                          os_overwrites:
                            alpine:
                              name: py3-pip

                    ##
                    ## opt-in default bundle for building py-pip libs
                    ##
                    py_deps_build:
                      enable: false
                      packages:
                        build-essential:
                          ## normally we only need it during image build and it should be removed again at the end
                          temporary: true
                          os_overwrites:
                            alpine:
                              name: build-base
                        python3-dev:
                          temporary: true
                        libffi-dev:
                          temporary: true
                        openssl-dev:
                          temporary: true

