---

  ##
  ## note: based on the current official way of
  ##   install which can be found here:
  ##
  ##     https://github.com/nodesource/distributions#installation-instructions
  ##
  nodejs_new:

    ##
    ## note: as most inherting images wont need it this
    ##   source is made opt-in, so an image which want
    ##   to use it must explicitly activate it
    ##
    disabled: true

    ## optional when using non standard apt keys
    signing:

      src_url: >-
        https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key

       ##dest: ## optional, defaults to: /etc/apt/keyrings/{mapkey}.asc

    ##apt_file: ## defaults to mapkey

    ## ## custom vars for source line templating
    ## TODO: auto-default to latest
    ## custom_vars:
    ##   ##node_major: 20

    source_line: >-
      deb {attributes} https://deb.nodesource.com/node_{node_major}.x nodistro main

